-- ============================================================
-- MIGRATION v13 - Documents are uploaded files, held on R2
-- Run this ONCE in your Supabase SQL Editor.
-- Idempotent: safe to re-run.
-- ============================================================
-- Supersedes the NAS-path approach in migration_v12. That one needed a
-- small program registered on every office PC before a link would
-- open, which is not something this practice can be asked to do - the
-- people using it are not technical and whoever maintains it is not in
-- the building. A feature needing a visit to each desk does not get
-- rolled out; it gets abandoned.
--
-- So a document is an uploaded file, chosen with an ordinary file
-- picker. Nothing is installed anywhere, and it works from outside the
-- office as well as in it.
--
-- WHY THE BYTES ARE NOT IN SUPABASE
--   The free plan allows 1 GB of storage and 5 GB of egress a month.
--   Site photos fit that because the browser caps them at 700 KB. A
--   drawing is fifteen times that, and every time somebody opens one
--   the whole file is egress. Ordinary use by a handful of staff would
--   pass 5 GB a month on its own, and the answer to that is $25 a
--   month forever.
--
--   Cloudflare R2 allows 10 GB free and charges nothing for egress on
--   any plan, ever. So the files go there and this database keeps only
--   the row describing them. What is left on Supabase is text, against
--   a 500 MB allowance this practice will not fill in years - which is
--   what keeps the whole system free rather than merely cheap.
--
-- WHERE PERMISSION IS DECIDED
--   R2 has no idea who anybody is. A Supabase Edge Function issues the
--   short-lived upload and download URLs, and it decides by querying
--   THIS database as the calling user - so the policies already in
--   migration_v8_confidential.sql are what answer, and a confidential
--   project's drawings stay unreachable without a second, hand-written
--   copy of that logic to get out of step.
--
--   That is also why storage_path is never chosen by the browser. The
--   function generates the key, and the browser only ever names a
--   project or a document id that RLS can adjudicate.
--
-- v12 IS NOT UNDONE HERE
--   documents.nas_path and app_settings are left in place. They hold
--   no data and dropping columns is not something to do casually. The
--   app no longer shows them. If they are still unused in a few
--   months, drop them then.
-- ============================================================


-- ─────────────────────────────────────────────────────────────
-- 1. What was uploaded
--    file_name is the name the file had on the person's machine, kept
--    because the object key is a UUID. Somebody downloading
--    "A-101 Rev C.pdf" should get that name back rather than
--    "9f3c....pdf", and this row is the only place it survives.
--
--    bytes is here so the practice can see what it is using without
--    asking R2 - see the usage query at the bottom.
-- ─────────────────────────────────────────────────────────────
alter table public.documents
  add column if not exists storage_path text,
  add column if not exists file_name    text,
  add column if not exists bytes        bigint,
  add column if not exists mime_type    text;

comment on column public.documents.storage_path is
  'Object key in the R2 bucket: <project_id>/<uuid>.<ext>. Generated by the edge function, never by the browser. NULL for a document that is only a link.';

-- One row per object. Two rows pointing at the same file would make
-- "delete this document" mean two different things.
create unique index if not exists documents_storage_path_unique
  on public.documents (storage_path) where storage_path is not null;

-- An uploaded file has to belong to a project. The edge function
-- decides who may read an object from the project id in its key, so a
-- file filed under no project has nothing to ask.
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'documents_upload_needs_project'
  ) then
    alter table public.documents add constraint documents_upload_needs_project check (
      storage_path is null or project_id is not null
    );
  end if;
end $$;


-- ─────────────────────────────────────────────────────────────
-- 2. No bucket and no storage policies
--    Nothing to create here on purpose. The bytes are not in Supabase,
--    and `storage.objects` policies would have nothing to guard.
--
--    The existing policies on public.documents already carry the whole
--    answer, and the edge function leans on exactly them:
--
--      "read documents"          - is_approved() and project_visible()
--      "member write documents"  - has_min_role('member') and
--                                  project_visible()
--
--    (both from migration_v8_confidential.sql)
-- ─────────────────────────────────────────────────────────────


-- ─────────────────────────────────────────────────────────────
-- 3. Sanity checks - paste these in afterwards
-- ─────────────────────────────────────────────────────────────
-- The columns exist:
--   select column_name, data_type from information_schema.columns
--    where table_schema = 'public' and table_name = 'documents'
--      and column_name in ('storage_path','file_name','bytes','mime_type')
--    order by column_name;
--
-- A file cannot be filed under no project:
--   insert into public.documents (name, storage_path)
--   values ('should fail', 'abc/def.pdf');
--   -- expected: violates check constraint documents_upload_needs_project
--
-- How much of the free 10 GB is in use:
--   select count(*)                        as files,
--          pg_size_pretty(sum(bytes))      as total
--     from public.documents
--    where storage_path is not null;
